name = "distracted-drivers-keras"
repo = "https://github.com/Mistobaan/distracted-drivers-keras.git"
description = "State Farm Distracted Driver Challenge"
environment = "tensorflow"

[datasets]
"fmilo/distracted-drivers-keras" = "0.0.2"
